spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Management_Cortexcam_BD
    username: postgres
    password: 2007
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/Management_Cortexcam_BD
    user: postgres
    password: 2007
    locations: classpath:db/migration

  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

jwt:
  secret: "TuSuperSecretoDeDesarrolloQueDebeTenerAlMenos32CaracteresParaHS256"
  expiration: 3600000
  header: Authorization
  prefix: Bearer

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
